# Generated by Django 3.2.13 on 2022-04-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_name', models.CharField(max_length=32)),
                ('dm_dean', models.CharField(max_length=32)),
                ('dm_phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=32)),
                ('major_teacher', models.CharField(max_length=32)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.department')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('other', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=32)),
                ('stu_class', models.CharField(max_length=64)),
                ('stu_phone', models.CharField(max_length=32)),
                ('stu_address', models.CharField(max_length=32)),
                ('stu_birthday', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.department')),
                ('stu_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.major')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_name', models.CharField(max_length=32)),
                ('classes_teacher', models.CharField(max_length=32)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maker.major')),
            ],
        ),
    ]
