# Generated by Django 3.2.13 on 2022-04-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_sex',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='usersex',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
