# Generated by Django 3.2.13 on 2022-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0003_auto_20220413_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
