# Generated by Django 3.2.13 on 2022-04-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0004_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='major',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
    ]
